name: Rust

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Upload VST (debug artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: VST Plug-In (Windows and Linux)
        path: |
          target/debug
          !target/debug/.fingerprint
          !target/debug/build
          !target/debug/deps
          !target/debug/examples
          !target/debug/incremental
          
